### ISSUE TITLE
Changes in the admin should create history entry as well

### ISSUE THREAD

**Issue by hheimbuerger** [nexto/django-model-audit-history#3]
Consider whether there's a reasonable way to make changes in the admin show up in the audit records as well.

If yes, present a rough concept how you would go about implementing this/integrating it into the admin.
If no, please argue why this shouldn't be done, what the risks are, etc.

**Comment by Killsoft1692** [comment]
we can do it by override save_model method in this way:
https://gist.github.com/Killsoft1692/b945283df1a8c419339b2ea9e0b32adc
Also new tests need to be added for this functionality
![screen shot 2019-01-26 at 1 23 39 am](https://user-images.githubusercontent.com/9252646/51778199-1a3ae380-2109-11e9-96a0-4486ba0c84fa.png)

**Comment by hheimbuerger** [comment]
That's great, let's for do that! Please use the event `CHANGE_VIA_ADMIN` for this case.

**Comment by Killsoft1692** [comment]
Done

**Comment by hheimbuerger** [comment]
Great, thanks!
